ans 1->

In [3]:
# ans 1->
import numpy as np

list_ = [ 1 , 2 , 3 , 4 , 5 ]

array_list = np.array(object = list_)
array_list

array([1, 2, 3, 4, 5])

In [4]:
list_

[1, 2, 3, 4, 5]

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

Yes, there is a difference in the data type of list_ and array_list. list_ is a Python list that contains
string elements, while array_list is a numpy array that also contains string elements.

ans 2->

In [9]:
 for i  in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [12]:
# ans 3->
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [13]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [14]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


no, there is no difference in data types of both variables and thee is not change in in array_list .

ans 4->

In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
num_array.shape

(2, 3)

In [23]:
num_array.size

6

In [ ]:
ans 5->

In [26]:
# ans 5->
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr.shape

(3, 3)

ans 6->


In [34]:
import numpy as np
arr1=np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr1.shape

(5, 5)